routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/** LOGIN */
Route::get('/', function () {
    return view('login');
});
Route::post('/checkLogin', 'UsersController@login');

/** DASHBOARD */
Route::get('/dashboard', function () {
    return view('dashboard.dashboard');
});

/** USER */
Route::get('/showCashier', function () {
    $users = DB::table('users')->get();
    return view('management.showCashier', ['users' => $users]);
});
Route::get('/createCashier', function () {
    return view('management.createCashier');
});
Route::post('/createCashierStart', 'UsersController@create');
Route::resource('users','UsersController');

/** PRODUK */
Route::get('/showProduct', function () {
    $products = DB::table('products')->get();
    return view('management.showProduct', ['products' => $products]);
});
Route::get('/createProduct', function () {
    return view('management.createProduct');
});
Route::post('/createProductStart', 'ProductsController@create');
Route::resource('products','ProductsController');
Route::get('/id/{id}/status/{status}', 'ProductsController@updateStatusProduct')->name('products.updateStatusProduct'); 

/** ORDER */
Route::get('/showOrder', function () {
    $users          = DB::table('users')->get();
    $products       = DB::table('products')->get();
    $orders         = DB::table('orders')->get();
    $transactions    = DB::table('transactions')->orderBy('updated_at', 'desc')->get();
    return view('transaction.showOrder', ['users' => $users, 'products' => $products, 'orders' => $orders, 'transactions' => $transactions]);
});
Route::get('/createOrder', function () {
    $products = DB::table('products')->get();
    return view('transaction.createOrder', ['products' => $products]);
});
Route::post('/createOrderStart', 'OrdersController@create');
Route::resource('orders','OrdersController');

/** PAYMENT */
Route::get('/showPayment', function () {
    $users          = DB::table('users')->get();
    $products       = DB::table('products')->get();
    $orders         = DB::table('orders')->get();
    $transactions    = DB::table('transactions')->orderBy('updated_at', 'asc')->get();
    return view('transaction.showPayment', ['users' => $users, 'products' => $products, 'orders' => $orders, 'transactions' => $transactions]);
});
Route::get('/id/{id}/cashamount/{cashamount}/cashback/{cashback}', 'OrdersController@updateStatusOrder')->name('payment.updateStatusOrder'); 

/** CLEAR CACHE */
Route::get('/cc', function() {
    $exitCode = Artisan::call('cache:clear');
    return view('login');
});

/** LOGOUT */
Route::get('/logoutCashier', 'UsersController@logout');

resources/views/transaction/createOrder.blade.php
@extends('menu.order')
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <?php $i=1;?>
<form action="{{ url('/createOrderStart') }}" method="POST">
Name : <input type="text" class="form-control" name="name" />
Table : <input type="text" class="form-control" name="no_table" />
<br/>
<button type="submit" class="form-control"><b>CREATE ORDER HERE</b></button>
<div class="row " style="padding-top: 50px;">
@foreach($products as $data)
@if($data->status!="Out Of Stock")
<?php $i++; ?>
{{ csrf_field() }} 
    <div class="col-md-4 ">    
        <div class="portfolio-item awesome mix_all" data-cat="awesome" style="display: inline-block; opacity: 1;">
            <img src="/img/{{$data->image}}" width="330px" height="250px">
            <div class="overlay">
                <p>
                    <span>
                    {{$data->name}}
                    </span>
                    <br/>
                    {{$data->price}}
                </p>
                <input type="number" class="form-control" name="{{$data->id}}" value="0" />
            </div>
        </div>   
    </div>
@endif
@endforeach
</div>
</form>   
@endsection

resources/views/transaction/editOrder.blade.php
@extends('menu.editOrder')
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <?php $i=1;?>
<form action="{{ route('orders.update',$id) }}" method="POST" enctype="multipart/form-data">
    Name : <input type="text" class="form-control" name="name" value="{{ $name }}" />
    Table : <input type="text" class="form-control" name="no_table" value="{{ $no_table }}" />
<br/>
<button type="submit" class="form-control"><b>UPDATE ORDER HERE</b></button>
<input type="hidden" class="form-control" id="id" name="id" value="{{ $id }}"/>
<div class="row " style="padding-top: 50px;">
@foreach($products as $data)
<?php $i++; ?>
{{ csrf_field() }}
{{ method_field('PUT') }}
    <div class="col-md-4 ">    
        <div class="portfolio-item awesome mix_all" data-cat="awesome" style="display: inline-block; opacity: 1;">
            <img src="/img/{{$data->image}}" width="330px" height="250px">
            <div class="overlay">
                <p>
                    <span>
                    {{$data->name}}
                    </span>
                    <br/>
                    {{$data->price}}
                </p>
                <?php $value=0; ?>
                @foreach($orders as $order)
                    @if($order->id_product == $data->id && $order->no == $id) 
                        <?php $value = $order->amount; ?>
                    @endif
                @endforeach
                    <input type="number" class="form-control" name="{{$data->id}}" value="{{ $value }}" />
            </div>
        </div>   
    </div>
@endforeach
</div>
</form>   
@endsection

resources/views/transaction/showOrder.blade.php
@extends('menu.order')
@section('content')

@if(session()->has('message'))
    <div class="alert alert-info">
        {{ session()->get('message') }}
    </div>
@elseif(session()->has('alert'))
    <div class="alert alert-danger">
        {{ session()->get('alert') }}
    </div>
@endif
<hr/>
<a class="btn btn-primary" href="createOrder"> + Create New Order</a>
<hr/>
<div class="panel panel-success">
    <div class="panel-heading">
    ORDER LIST
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Table</th>
                        <th>No Transaction</th>
                        <th>Order(Amount)</th>
                        <th>Waiter</th>
                        <th>Status</th>
                        <th>Operation</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $i=1; ?>
                    @foreach($transactions as $data)
                    @if($data->status!="Paid Off")
                    <form action="{{ route('orders.destroy',$data->no_order) }}" method="POST">
                        <tr>
                            <td><?php echo $i++; ?></td>
                            <td>{{$data->name}}</td>
                            <td>{{$data->no_table}}</td>
                            <td>{{$data->no_order}}</td>
                            <td>
                                @foreach($orders as $order)
                                    @if($data->no_order == $order->no)
                                        @foreach($products as $product)
                                            @if($order->id_product == $product->id)
                                                {{ $product->name }} ({{ $order->amount }})<br/>
                                            @endif
                                        @endforeach
                                    @endif
                                @endforeach
                            </td>
                            <td>
                                @foreach($users as $user)
                                    @if($data->id_cashier == $user->id)
                                        {{ $user->name }}
                                    @endif
                                @endforeach
                            </td>
                            <td>{{$data->status}}</td>
                            <td align=center>
                                <a class="btn btn-primary" href="{{ route('orders.edit',$data->no_order) }}">Edit</a>
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </td>
                        </tr>     
                    </form>
                    @endif
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/transaction/showPayment.blade.php
@extends('menu.payment')
@section('content')

@if(session()->has('message'))
    <div class="alert alert-info">
        {{ session()->get('message') }}
    </div>
@elseif(session()->has('alert'))
    <div class="alert alert-danger">
        {{ session()->get('alert') }}
    </div>
@endif
<div class="panel panel-success">
    <div class="panel-heading">
    PAYMENT LIST
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Table</th>
                        <th>No Transaction</th>
                        <th>Order(Amount)</th>
                        <th>Waiter</th>
                        <th>Total</th>
                        <th>Status</th>
                        <th>Operation</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $i=1; ?>
                    @foreach($transactions as $data)
                    @if($data->status!="Paid Off")
                        <tr>
                            <td><?php echo $i++; ?></td>
                            <td>{{$data->name}}</td>
                            <td>{{$data->no_table}}</td>
                            <td>{{$data->no_order}}</td>
                            <td>
                                @foreach($orders as $order)
                                    @if($data->no_order == $order->no)
                                        @foreach($products as $product)
                                            @if($order->id_product == $product->id)
                                                {{ $product->name }} ({{ $order->amount }})<br/>
                                            @endif
                                        @endforeach
                                    @endif
                                @endforeach
                            </td>
                            <td>
                                @foreach($users as $user)
                                    @if($data->id_cashier == $user->id)
                                        {{ $user->name }}
                                    @endif
                                @endforeach
                            </td>
                            <td>{{$data->total}}</td>
                            <td>{{$data->status}}</td>
                            <td align=center>
                                <button class="btn btn-danger" data-toggle="modal" data-target="#myModal{{$data->no_order}}"> PAY </button>
                            </td>
                        </tr>
                    @endif
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
 </div>
<hr/>
<div class="panel panel-success">
    <div class="panel-heading">
    PAID LIST
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Table</th>
                        <th>No Transaction</th>
                        <th>Order(Amount)</th>
                        <th>Waiter</th>
                        <th>Total</th>
                        <th>Status</th>
                        <th>Operation</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $i=1; ?>
                    @foreach($transactions as $data)
                    @if($data->status!="Booked")
                        <tr>
                            <td><?php echo $i++; ?></td>
                            <td>{{$data->name}}</td>
                            <td>{{$data->no_table}}</td>
                            <td>{{$data->no_order}}</td>
                            <td>
                                @foreach($orders as $order)
                                    @if($data->no_order == $order->no)
                                        @foreach($products as $product)
                                            @if($order->id_product == $product->id)
                                                {{ $product->name }} ({{ $order->amount }})<br/>
                                            @endif
                                        @endforeach
                                    @endif
                                @endforeach
                            </td>
                            <td>
                                @foreach($users as $user)
                                    @if($data->id_cashier == $user->id)
                                        {{ $user->name }}
                                    @endif
                                @endforeach
                            </td>
                            <td>{{$data->total}}</td>
                            <td>{{$data->status}}</td>
                            <td align=center>
                                <button class="btn btn-primary" data-toggle="modal" data-target="#myModal{{$data->no_order}}"> DETAIL </button>
                            </td>
                        </tr>     
                    @endif
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
 </div>


@foreach($transactions as $data)
<div class="modal fade" id="myModal{{$data->no_order}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">Payment Details</h4>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <tr>
                            <td>Name</td>
                            <td>Price</td>
                            <td>Amount</td>
                            <td>Total</td>
                        </tr>
                    <?php $total=0; ?>
                    @foreach($orders as $order)
                        @if($data->no_order == $order->no)
                            @foreach($products as $product)
                                @if($order->id_product == $product->id)
                                <tr>
                                    <td>{{ $product->name }}</td>
                                    <td>{{ $product->price }}</td>
                                    <td>{{ $order->amount }}</td>
                                    <td>{{ $product->price*$order->amount }}</td>
                                    <?php $total = $total+($product->price*$order->amount); ?>
                                </tr>
                                @endif
                            @endforeach
                        @endif
                    @endforeach
                        <tr>
                            <td colspan="3">Total Payment</td>
                            <td><?php echo $total; ?></td>
                        </tr>
                    </table>
                    @if($data->status!="Paid Off")
                    <table class="table table-striped table-bordered table-hover">
                        <tr>
                            <td>Total Payment</td>
                            <td><input type="number" class="form-control" id="total{{$data->id}}" name="total{{$data->id}}" value="<?php echo $total; ?>" readonly/></td>
                        </tr>
                        <tr>
                            <td>Cash Amount</td>
                            <td><input type="number" class="form-control" id="cashamount{{$data->id}}" name="cashamount{{$data->id}}" onkeyup="count('{{$data->id}}')" /></td>
                        </tr>
                        <tr>
                            <td>Cashback</td>
                            <td><input type="number" class="form-control" id="cashback{{$data->id}}" name="cashback{{$data->id}}" readonly/></td>
                        </tr>
                    </table>
                    @endif
                    @if($data->status=="Paid Off")
                    <table class="table table-striped table-bordered table-hover">
                        <tr>
                            <td>Total Payment</td>
                            <td>{{$data->total}}</td>
                        </tr>
                        <tr>
                            <td>Cash Amount</td>
                            <td>{{$data->cashamount}}</td>
                        </tr>
                        <tr>
                            <td>Cashback</td>
                            <td>{{$data->cashback}}</td>
                        </tr>
                    </table>
                    @endif
                </div>
            </div>
            <div class="modal-footer">
                @if($data->status!="Paid Off")
                    <a href='#' onclick="this.href='/id/{{$data->id}}/cashamount/'+document.getElementById('cashamount{{$data->id}}').value+'/cashback/'+document.getElementById('cashback{{$data->id}}').value"><button type="button" class="btn btn-primary">Pay Bills</button></a>
                @endif
                @if($data->status=="Paid Off")
                    <a href='#' onclick="this.href='/id/{{$data->id}}/cashamount/'+document.getElementById('cashamount{{$data->id}}').value+'/cashback/'+document.getElementById('cashback{{$data->id}}').value"><button type="button" class="btn btn-primary">Print</button></a>
                @endif
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
function count(id) {
  var total         = document.getElementById("total"+id).value;
  var cashamount    = document.getElementById("cashamount"+id).value;
  var result        = cashamount-total;
  document.getElementById("cashback"+id).value = result;
}
</script>
@endforeach
@endsection