routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/** LOGIN */
Route::get('/', function () {
    return view('login');
});
Route::post('/checkLogin', 'UsersController@login');

/** DASHBOARD */
Route::get('/dashboard', function () {
    return view('dashboard.dashboard');
});

/** USER */
Route::get('/showCashier', function () {
    $users = DB::table('users')->get();
    return view('management.showCashier', ['users' => $users]);
});
Route::get('/createCashier', function () {
    return view('management.createCashier');
});
Route::post('/createCashierStart', 'UsersController@create');
Route::resource('users','UsersController');

/** PRODUK */
Route::get('/showProduct', function () {
    $products = DB::table('products')->get();
    return view('management.showProduct', ['products' => $products]);
});
Route::get('/createProduct', function () {
    return view('management.createProduct');
});
Route::post('/createProductStart', 'ProductsController@create');
Route::resource('products','ProductsController');
Route::get('/id/{id}/status/{status}', 'ProductsController@updateStatusProduct')->name('products.updateStatusProduct'); 

/** ORDER */
Route::get('/showOrder', function () {
    $users          = DB::table('users')->get();
    $products       = DB::table('products')->get();
    $orders         = DB::table('orders')->get();
    $transactions    = DB::table('transactions')->orderBy('updated_at', 'desc')->get();
    return view('transaction.showOrder', ['users' => $users, 'products' => $products, 'orders' => $orders, 'transactions' => $transactions]);
});
Route::get('/createOrder', function () {
    $products = DB::table('products')->get();
    return view('transaction.createOrder', ['products' => $products]);
});
Route::post('/createOrderStart', 'OrdersController@create');
Route::resource('orders','OrdersController');

/** PAYMENT */
Route::get('/showPayment', function () {
    $users          = DB::table('users')->get();
    $products       = DB::table('products')->get();
    $orders         = DB::table('orders')->get();
    $transactions    = DB::table('transactions')->orderBy('updated_at', 'asc')->get();
    return view('transaction.showPayment', ['users' => $users, 'products' => $products, 'orders' => $orders, 'transactions' => $transactions]);
});
Route::get('/id/{id}/cashamount/{cashamount}/cashback/{cashback}', 'OrdersController@updateStatusOrder')->name('payment.updateStatusOrder'); 

/** CLEAR CACHE */
Route::get('/cc', function() {
    $exitCode = Artisan::call('cache:clear');
    return view('login');
});

/** LOGOUT */
Route::get('/logoutCashier', 'UsersController@logout');

resources/views/management/createCashier.blade.php
@extends('menu.cashier')
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    
    <section class="main-section">
        <div class="content">
            <form action="{{ url('/createCashierStart') }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" id="name" name="name" />
                </div>
                <div class="form-group">
                    <label for="name">Username:</label>
                    <input type="text" class="form-control" id="username" name="username" />
                </div>
                <div class="form-group">
                    <label for="name">Password:</label>
                    <input type="password" class="form-control" id="password" name="password" />
                </div>
                <div class="form-group">
                    <label for="name">Password Confirmation:</label>
                    <input type="password" class="form-control" id="confirmation" name="confirmation" />
                </div>
                <div class="form-group">
                    <label for="name">Gender:</label>
                    <select name="gender" class="form-control">
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="name">Authorization:</label>
                    <select name="authorization" class="form-control">
                        <option value="Admin">Admin</option>
                        <option value="Cashier">Cashier</option>
                        <option value="Cashier">Waiter</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="name">Photo:</label>
                    <input type="file" class="form-control" id="image" name="image" />
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-md btn-primary">Create New Cashier</button>
                </div>
            </form>
        </div>
    </section>
@endsection

resources/views/management/createProduct.blade.php
@extends('menu.product')
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <section class="main-section">
        <div class="content">
            <form action="{{ url('/createProductStart') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text"  class="form-control" id="name" name="name">
                </div>
                <div class="form-group">
                    <label for="name">Type:</label>
                    <select name="type" class="form-control">
                        <option value="Food">Food</option>
                        <option value="Drink">Drink</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="name">Price:</label>
                    <input type="number" class="form-control" id="price" name="price">
                </div>
                <div class="form-group">
                    <label for="name">Status:</label>
                    <select name="status" class="form-control">
                        <option value="Ready">Ready</option>
                        <option value="Out Of Stock">Out Of Stock</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="name">File</label>
                    <input type="file" class="form-control" id="image" name="image">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-md btn-primary">Create New Product</button>
                </div>
            </form>
        </div>
    </section>
@endsection

resources/views/management/editCashier.blade.php
@extends('menu.editCashier')
@section('content')

@if(session()->has('message'))
    <div class="alert alert-success">
        {{ session()->get('message') }}
    </div>
@endif
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    @foreach($data as $datas)
    <form action="{{ route('users.update',$datas->id) }}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        <div class="form-group">
            <label for="name">Nama:</label>
            <input type="text"  class="form-control" id="name" name="name" value="{{ $datas->name }}" />
        </div>
        <div class="form-group">
            <label for="name">Username:</label>
            <input type="text"  class="form-control" id="username" name="username" value="{{ $datas->username }}" />
        </div>
        <div class="form-group">
            <label for="name">Password:</label>
            <input type="password" class="form-control" id="password" name="password" value="{{ $datas->password }}" />
        </div>
        <div class="form-group">
            <label for="name">Password Confirmation:</label>
            <input type="password" class="form-control" id="confirmation" name="confirmation" />
        </div>
        <div class="form-group">
            <label for="name">Gender:</label>
            <select name="gender" class="form-control">
                <option value="Male" {{old('admin',$datas->gender)=="Male"? 'selected':''}}>Male</option>
                <option value="Female" {{old('admin',$datas->gender)=="Female"? 'selected':''}}>Female</option>
            </select>
        </div>
        <div class="form-group">
            <label for="name">Authorization:</label>
            <select name="authorization" class="form-control">
                <option value="Admin" {{old('admin',$datas->authorization)=="Admin"? 'selected':''}}>Admin</option>
                <option value="Cashier" {{old('admin',$datas->authorization)=="Cashier"? 'selected':''}}>Cashier</option>
                <option value="Waiter" {{old('admin',$datas->authorization)=="Waiter"? 'selected':''}}>Waiter</option>
            </select>
        </div>
        <div class="form-group">
            <img src="{{ URL::asset('img/'.$datas->image) }}" class="img-thumbnail" width="100px" height="100px" />
        </div>
        <div class="form-group">
            <label for="name">Photo:</label>
            <input type="file" class="form-control" id="image" name="image" />
        </div>
        <div class="form-group">
            <input type="hidden" class="form-control" id="id" name="id" value="{{ $datas->id }}"/>
            <button type="submit" class="btn btn-md btn-primary">Update Cashier</button>
        </div>
    </form>
    @endforeach
@endsection

resources/views/management/editProduct.blade.php
@extends('menu.editProduct')
@section('content')

@if(session()->has('message'))
    <div class="alert alert-success">
        {{ session()->get('message') }}
    </div>
@endif
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    @foreach($data as $datas)
    <form action="{{ route('products.update',$datas->id) }}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text"  class="form-control" id="name" name="name" value="{{ $datas->name }}">
                </div>
                <div class="form-group">
                    <label for="name">Type:</label>
                    <select name="type" class="form-control">
                        <option value="Food" {{old('type',$datas->type)=="Food"? 'selected':''}}>Food</option>
                        <option value="Drink" {{old('type',$datas->type)=="Drink"? 'selected':''}}>Drink</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="name">Price:</label>
                    <input type="number" class="form-control" id="price" name="price" value="{{ $datas->price }}">
                </div>
                <div class="form-group">
                    <label for="name">Status:</label>
                    <select name="status" class="form-control">
                        <option value="Ready" {{old('status',$datas->status)=="Ready"? 'selected':''}}>Ready</option>
                        <option value="Out Of Stock" {{old('status',$datas->status)=="Out Of Stock"? 'selected':''}}>Out Of Stock</option>
                    </select>
                </div>
                <div class="form-group">
                    <img src="{{ URL::asset('img/'.$datas->image) }}" class="img-thumbnail" width="100px" height="100px" />
                </div>
                <div class="form-group">
                    <label for="name">Photo:</label>
                    <input type="file" class="form-control" id="image" name="image"/>
                </div>
                <div class="form-group">
                    <input type="hidden" class="form-control" id="id" name="id" value="{{ $datas->id }}"/>
                    <button type="submit" class="btn btn-md btn-primary">Update Product</button>
                </div>
    </form>
    @endforeach
@endsection

resources/views/management/showCashier.blade.php
@extends('menu.cashier')
@section('content')

@if(session()->has('message'))
    <div class="alert alert-info">
        {{ session()->get('message') }}
    </div>
@elseif(session()->has('alert'))
    <div class="alert alert-danger">
        {{ session()->get('alert') }}
    </div>
@endif
<hr/>
<a class="btn btn-primary" href="createCashier"> + Create New Cashier</a>
<hr/>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Gender</th>
                <th>Username</th>
                <th>Authorization</th>
                <th>Operation</th>
            </tr>
        </thead>
        <tbody>
            <?php $i=1; ?>
            @foreach($users as $data)
            <form action="{{ route('users.destroy',$data->id) }}" method="POST">
                <tr class="success">
                    <td><?php echo $i++; ?></td>
                    <td>{{$data->name}}</td>
                    <td>{{$data->gender}}</td>
                    <td>{{$data->username}}</td>
                    <td>{{$data->authorization}}</td>
                    <td align=center>
                        <a class="btn btn-primary" href="{{ route('users.edit',$data->id) }}">Edit</a>
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </td>
                </tr>     
                </form>
            @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/management/showProduct.blade.php
@extends('menu.product')
@section('content')

@if(session()->has('message'))
    <div class="alert alert-info">
        {{ session()->get('message') }}
    </div>
@elseif(session()->has('alert'))
    <div class="alert alert-danger">
        {{ session()->get('alert') }}
    </div>
@endif
<hr/>
<a class="btn btn-primary" href="createProduct"> + Create New Product</a>
<hr/>
<div class="panel panel-success">
    <div class="panel-heading">
    PRODUCT LIST
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Price</th>
                        <th>Status</th>
                        <th>Update Status</th>
                        <th>Photo</th>
                        <th>Operation</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $i=1; ?>
                    @foreach($products as $data)
                    <form action="{{ route('products.destroy',$data->id) }}" method="POST">
                        <tr>
                            <td><?php echo $i++; ?></td>
                            <td>{{$data->name}}</td>
                            <td>{{$data->type}}</td>
                            <td>{{$data->price}}</td>
                            <td>{{$data->status}}</td>
                            <td>
                                @if($data->status=="Ready")
                                <a class="btn btn-primary" href="{{ route('products.updateStatusProduct',['id' => $data->id, 'status' => 'Out Of Stock']) }}">Out Of Stock</a>
                                @else
                                <a class="btn btn-primary" href="{{ route('products.updateStatusProduct',['id' => $data->id, 'status' => 'Ready']) }}">Ready</a>
                                @endif
                            </td>
                            <td><img src="{{ URL::asset('img/'.$data->image) }}" width="75px" height="50px"/></td>
                            <td align=center>
                                <a class="btn btn-primary" href="{{ route('products.edit',$data->id) }}">Edit</a>
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </td>
                        </tr>     
                        </form>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection